# Generated by Django 5.2.6 on 2025-09-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='apellidos',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
